import logging
from typing import Any, List, Tuple

import numpy as np

from documents.models import DocumentChunk

logger = logging.getLogger(__name__)


def compute_cosine_similarity(
    vec1: List[float],
    vec2: List[float],
) -> float:
    """
    Calculate cosine similarity between two embedding vectors.
    """

    try:
        v1 = np.asarray(vec1, dtype=np.float32)
        v2 = np.asarray(vec2, dtype=np.float32)

        if v1.ndim != 1 or v2.ndim != 1:
            return 0.0

        # Prevent NumPy dot-product errors if embeddings
        # were generated by different models/dimensions.
        if v1.shape[0] != v2.shape[0]:
            logger.warning(
                "Embedding dimension mismatch: %s vs %s",
                v1.shape[0],
                v2.shape[0],
            )
            return 0.0

        norm_v1 = np.linalg.norm(v1)
        norm_v2 = np.linalg.norm(v2)

        if norm_v1 == 0.0 or norm_v2 == 0.0:
            return 0.0

        return float(
            np.dot(v1, v2) / (norm_v1 * norm_v2)
        )

    except (TypeError, ValueError):
        logger.exception(
            "Failed to calculate cosine similarity"
        )
        return 0.0


def delete_document_vectors(
    document_id: Any,
    user_id: Any,
) -> int:
    """
    Delete all stored document chunks belonging to the
    specified document and user.
    """

    deleted_count, _ = DocumentChunk.objects.filter(
        document_id=document_id,
        user_id=user_id,
    ).delete()

    logger.info(
        "Deleted %s chunks for document_id=%s",
        deleted_count,
        document_id,
    )

    return deleted_count


def similarity_search_with_relevance_scores(
    query: str,
    user_id: Any,
    conversation_id: Any,
    embedding_model: Any,
    k: int = 5,
    score_threshold: float = 0.2,
) -> List[Tuple[Any, float]]:
    """
    Retrieve document chunks for one user/conversation
    and rank them using cosine similarity.
    """

    try:
        # Generate embedding for the user's query.
        query_embedding = embedding_model.embed_query(query)

        if not query_embedding:
            logger.warning("Empty query embedding.")
            return []

        # Retrieve only chunks belonging to this user
        # and conversation.
        chunks = DocumentChunk.objects.filter(
            user_id=user_id,
            conversation_id=conversation_id,
        ).only(
            "id",
            "document_id",
            "content",
            "embedding",
            "filename",
            "file_type",
            "page",
            "chunk_index",
        )

        scored_results = []

        for chunk in chunks:
            chunk_embedding = chunk.embedding

            if not chunk_embedding:
                continue

            score = compute_cosine_similarity(
                query_embedding,
                chunk_embedding,
            )

            if score >= score_threshold:
                scored_results.append(
                    (chunk, score)
                )

        # Highest similarity first.
        scored_results.sort(
            key=lambda item: item[1],
            reverse=True,
        )

        return scored_results[:k]

    except Exception:
        logger.exception(
            "Vector similarity search failed"
        )
        return []